version: '3'

services:
  app:
    image: xuanbachdao0212/frontend
    container_name: ie303.n21.frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always