version: '3'

services:
  app:
    container_name: ie303.n21.frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: nginx -g 'daemon off;'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
